### ISSUE TITLE
Can you help with Maya2020

### ISSUE THREAD

**Issue by zhai23** [akasaki1211/colDetectionNode#1]
Can you help with Maya2020

**Comment by akasaki1211** [comment]
Thank you @zhai23. 
Added pre-built plug-ins for Maya2020.4 with commit 005f69739c023337cadb69b6c7ae280620ce9622.
If you notice anything else, please open a new Issue.

[`plug-ins/2020/colDetectionNode.mll`](https://github.com/akasaki1211/colDetectionNode/blob/main/plug-ins/2020/colDetectionNode.mll)
